### ISSUE TITLE
No absence points showing up (the black dots) on the maps

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1986]
Original report: https://rfcx.slack.com/archives/C03FD1WD02J/p1715954314907769
@carlybatist 

There are no absence points showing up (the black dots) on the map, but there are >10 sites that have no detections for this species and should be showing up. Same problem on the Highlights, Richness, and Activity page.
Project: https://arbimon.org/p/cofav2022/insights/spotlight/varecia-variegata
![Image](https://github.com/rfcx/arbimon/assets/87486094/8e90f024-c790-4e72-aef4-f8149cd4558e)

I've checked a few other projects and the issue does not appear in those. e.g., -
https://arbimon.org/p/bci-panama-2018/insights/spotlight/ateles-geoffroyi
https://arbimon.org/p/chile-nahuelbuta-biodiversity-monitoring/insights/spotlight/agelasticus-thilius

![Image](https://github.com/rfcx/arbimon/assets/87486094/518ef8f2-21dc-4de1-b041-312bd1efab0d)

**Comment by grindarius** [comment]
After giving the code a read, I found that the spotlight API will return the summary informations about the site only for the site that have detections.

I went into the database and found that although all sites in cofav2022 have recordings, only 10 of them have detections, that makes the API return only 10 sites that have detections.

For bci-panama-2018, They have 113 sites, 112 of them have recordings and 99 of them have detections.

The spotlight API for bci-panama-2018 returns 99 sites with some of the site's detectionsMinutesCount being 0... but that does not mean that the site does not have any detections, it's because the site does not have any detection from given speciesId...

**Comment by carlybatist** [comment]
> After giving the code a read, I found that the spotlight API will return the summary informations about the site only for the site that have detections.
> 
> The blue dot on the UI means those are the sites that have detections and also include detections of that given species.
> 
> The black dot on the UI means those are the sites that have detections but does not have detections of given species.
> 
> Since cofav2022 have only 1 species detected. That means that there will be no black dots since all the sites that have detections are on this one single species.
> 
> @koonchaya @carlybatist

Ok thanks for the clarification! I do think it would make more sense to change the spotlight API so that if a project only has 1 species, the black dots still show up. The spotlight page should be species-specific information, so the site dots should reflect whether that species is detected at a site or not. Is this something you could create a ticket to change? Would it be a ton of effort to do that? If so we can skip, but if it's a fairly easy fix it would be good to make this change.

**Comment by grindarius** [comment]
I think the fix can be either change the behavior of the black dot to be "a site that have recordings or a site that have both recordings and detections but not for the selected species". So that it's consistent over all projects. or we provide better documenation.

It's not too much of a work to make changes to fit that, probably a day and couple more days of testing. @carlybatist @koonchaya

**Comment by carlybatist** [comment]
Let's hold off for now given what we talked about in the last sprint review. I can edit the support docs to state more specifically what the colored dots mean
