### ISSUE TITLE
Investigate project backup export from biosoundscape project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2037]
Original report: https://rfcx.slack.com/archives/C03FD1WD02J/p1718028385095719
@carlybatist 

User reported that number of recordings and templates exported from the project didn't match data in the project.
Project https://arbimon.org/p/biosoundscape/overview

>"When I made a backup of our BioSoundSCape project, the zip did not include the recordings.csv that has the AWS links to recordings.   This file is invaluable. Also, it doesn't appear that we got a full list of templates in templates.csv. Maybe this is because there is a lot of data in BioSoundSCape?"
>This project - https://arbimon.org/p/biosoundscape/overview

Additional information
I exported the files from the project and found that the number of recordings and templates didn't match. 
Export file https://drive.google.com/file/d/1_l2LmgDrn_CIMDx23Bq5JWIlVhmF15A2/view?usp=sharing

**Comment by grindarius** [comment]
I dug up the logs and found that it's an error at the SQL level. Most statements failed to run when the server is likely at its max.  See error images below...

<img width="1431" alt="Screenshot 2567-06-14 at 13 03 13" src="https://github.com/rfcx/arbimon/assets/60266519/7e489a9e-7135-4a25-a8e0-9cddddf5745c">
<img width="1433" alt="Screenshot 2567-06-14 at 13 03 36" src="https://github.com/rfcx/arbimon/assets/60266519/761bef82-74bc-4dde-b1b4-3930d4cc279f">
<img width="1430" alt="Screenshot 2567-06-14 at 13 03 49" src="https://github.com/rfcx/arbimon/assets/60266519/6482edfe-9e51-49a9-9536-c1c67999228b">
<img width="1419" alt="Screenshot 2567-06-14 at 13 04 04" src="https://github.com/rfcx/arbimon/assets/60266519/4b5cdeae-f2dc-4a11-8528-40ce9f96ee75">

It's an error from legacy, but since our backup system is designed to be fault-tolerant, they can still do an export even if all queries failed.

The problem is the query took too long to do so. I guess there are a couple places where we can improve it.
- Index-based pointer on tables that have sortable index.
- Reduce database chunk query to something like 50k but still save the file at 200k rows as normal.

**Comment by carlybatist** [comment]
@grindarius ok how long do you anticipate it will take to implement these fixes so that we can check if they work? 
We need to be able to have large projects work with the backup. And if there is an error where not all rows are going to show up, there needs to be an error message to the user demonstrating that. The user only realized this was a problem when they double-checked the CSVs against the project data.

**Comment by antonyharfield** [comment]
> Reduce database chunk query to something like 50k 

That sounds reasonable.

This query is very light because the only ordering is by PK so it shouldn't need to do much to read this data. It more likely failed because there was a lot of db activity at the same time. We could try some exponential backoff: if a query fails then retry in 10 sec, then 20 sec, then 40 sec then 80 sec else fail completely.

If one of the queries fails then I think the whole job should fail -- we don't want to continue and send the user incomplete data.

@carlybatist We are going to need this week to work on some improvements.

**Comment by koonchaya** [comment]
Email fail status to user and support@rfcx.org/slack

**Comment by koonchaya** [comment]
Draft email to notify failure export:

Subject: Arbimon project export failed

Hello,

Thanks so much for using Arbimon! We encountered an issue while backing up your project '...'. Our apologies for the inconvenience. Please contact our support team at [contact@arbimon.org] for assistance.

@antonyharfield @carlybatist Can you check if this message need any changes?

**Comment by carlybatist** [comment]
@koonchaya 
Tech team would be getting this error notification too right? They should then immediately start looking into it as a support ticket. So I would think the email to the user should be informing them that there was an error and that our team is looking into it and will update them. Noon and I should be auto-cc'd on these emails to users too. So it would be --


Hello,

There was an issue with your project backup of '...'. Our engineering team is looking into this and will update you when we have resolved it. We apologize for the inconvenience and thank you for your patience! 

All the best,
Arbimon team

**Comment by carlybatist** [comment]
@koonchaya @grindarius what do you expect the timeline for fixing the underlying issue will be?

**Comment by koonchaya** [comment]
I tested export backup from project https://staging.arbimon.org/p/bci-panama-2018/overview
@grindarius here is some feedback

- playlists.csv is empty - there are a lot of playlists in the project (https://staging.arbimon.org/project/bci-panama-2018/audiodata/playlists) 


[playlists.csv](https://github.com/user-attachments/files/15936970/playlists.csv)


- pattern_matchings.csv is empty but there are some jobs in the project (https://staging.arbimon.org/project/bci-panama-2018/analysis/patternmatching)

[pattern_matchings.csv](https://github.com/user-attachments/files/15936968/pattern_matchings.csv)


- pattern_matching_rois.csv is empty but there should be some rois data 

[pattern_matching_rois.csv](https://github.com/user-attachments/files/15936976/pattern_matching_rois.csv)


- recordings.csv is empty but there are 128546 Recordings in the project (https://staging.arbimon.org/project/bci-panama-2018/audiodata/recordings)


[recordings.csv](https://github.com/user-attachments/files/15936981/recordings.csv)


- recording_validations.csv is empty but there are some validations in the project 

[recording_validations.csv](https://github.com/user-attachments/files/15937013/recording_validations.csv)


![Image](https://github.com/rfcx/arbimon/assets/87486094/a915e5b5-0947-4ca9-8efa-c6b96d0d32f9)


- rfm_models.csv is empty 

[rfm_models.csv](https://github.com/user-attachments/files/15937094/rfm_models.csv)


- sites.csv is empty 

[sites.csv](https://github.com/user-attachments/files/15937096/sites.csv)


- soundscapes.csv is empty 

[soundscapes.csv](https://github.com/user-attachments/files/15937097/soundscapes.csv)


- species.csv is empty 

[species.csv](https://github.com/user-attachments/files/15937098/species.csv)


- templates.csv is empty

[templates.csv](https://github.com/user-attachments/files/15937099/templates.csv)

**Comment by koonchaya** [comment]
@grindarius 
- pattern_matchings.csv has more PM jobs than listed in the project. Test project https://staging.arbimon.org/project/bci-panama-2018/analysis/patternmatching

[pattern_matchings.csv](https://github.com/user-attachments/files/15951366/pattern_matchings.csv)

and I believe the pattern_matching_rois.csv contains the same data as above which are from the PM jobs that not listed in the project. 

[pattern_matching_rois.csv](https://github.com/user-attachments/files/15951394/pattern_matching_rois.csv)

**Comment by grindarius** [comment]
For pattern matchings export, we grab data directly from `pattern_matchings` table. What you see in the UI are jobs that are joined with the `jobs` table. But in `pattern_matchings` table we can get all the jobs from there even some jobs are not related to the `jobs` table. Same goes for `pattern_matching_rois`.

For playlists export I did find both playlists inside the export file so it's all good.

For rfm models there are deleted models being exported into the file.

Same goes for rfm classifications, we did not have condition to remove deleted classifications out.

**Comment by RatreeOchn** [comment]
Released on [v1.4.2](https://github.com/rfcx/arbimon/releases/tag/v1.4.2)

**Comment by carlybatist** [comment]
@koonchaya I see this is closed - can I tell the user to try the backup again? Or is there still more work to be done for the backup performance

**Comment by grindarius** [comment]
> @koonchaya I see this is closed - can I tell the user to try the backup again? Or is there still more work to be done for the backup performance

@carlybatist We are testing the perf upgrades on staging right now. I would expect the user to be able to export all the files tomorrow. I have yet to get all of the performance changes onto production because I wanted to make sure we did not miss anything.

**Comment by carlybatist** [comment]
Ok no worries thanks for the update! Just wasn't sure of the status since the issue had been 'closed'.
