### ISSUE TITLE
Species should not show on Insights when there is no species detection in the project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2053]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1718645778204739

Project: https://arbimon.org/p/tnc-rfcx-biodiversity-in-parque-nacional-braulio-carrillo-and-la-selva-oet/insights/spotlight/micrastur-semitorquatus

Micrastur semitorquatus shows in Insights, but there are not recordings with it validated (see attached screenshot). Therefore, the species should be removed from Insights.

![Image](https://github.com/rfcx/arbimon/assets/87486094/dda986a0-3a02-41c5-81e0-f2df8ceeaccf)

![Image](https://github.com/rfcx/arbimon/assets/87486094/aab5a448-471e-4d73-b49e-eb7cecda6024)

**Comment by rassokhina-e** [comment]
The site related to the original recording where was validated Micrastur semitorquatus species was moved to another project Monitoreo bioacustico en ITAIPU BINACIONAL_BMAP . The project was updated in the site , but recordings validations not, because it was at the start of this year, we implemented removing the validations when the user moves site to another project later.

I removed the validation, so we just have to wait 5 mins of incremental sync and recheck it on the bio side @koonchaya

**Comment by koonchaya** [comment]
@rassokhina-e We can remove the species manually from this project.

**Comment by koonchaya** [comment]
![Image](https://github.com/rfcx/arbimon/assets/87486094/2a6b093f-1ba5-41d3-b548-f09caa39a7c2)
